In [ ]:
#! pip3 install openpyxl
#! pip3 install sentence_transformers

In [2]:
import pandas as pd
import numpy as np
import psycopg2
import requests
import re
import time
from sentence_transformers import SentenceTransformer

/home/user03/Documents/SVN/UrFU.term3/Hackaton2023/.venv/lib/python3.10/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

# Справочник Вузов (первая закладка)

In [3]:
edu_df = pd.read_excel('Вузы РФ (от 07.12.23).xlsx')

In [39]:
edu_df

,IsFederal,Id,StatusName,StatusCode,TypeName,TypeCode,RegionName,RegionCode,FederalDistrictName,FederalDistrictShortName,...,StartedSupplementIssueDate,StoppedSupplementId,StoppedSupplementNumber,StoppedSupplementSerialNumber,StoppedSupplementFormNumber,StoppedSupplementIssueDate,OldRegNumber,OldSerialNumber,OldFormNumber,OldIssueDate
0,NaN,000000de-9b01-0511-a861-69d27006612a,Недействующее,NaN,Не определен,Unknown,Тверская область,69.0,Центральный федеральный округ,ЦФО,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,000000de-9b01-0511-a861-69d27006612a,Недействующее,NaN,Не определен,Unknown,Тверская область,69.0,Центральный федеральный округ,ЦФО,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,000000de-9b01-0511-a861-69d27006612a,Недействующее,NaN,Не определен,Unknown,Тверская область,69.0,Центральный федеральный округ,ЦФО,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,000000de-9b01-0511-a861-69d27006612a,Недействующее,NaN,Не определен,Unknown,Тверская область,69.0,Центральный федеральный округ,ЦФО,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,0000ff25-0c15-41a8-ad87-17a739919454,Действующее,InForce,Не определен,Unknown,Свердловская область,66.0,Уральский федеральный округ,УФО,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
692566,1.0,ffffdaa5-0b87-4774-bc2a-f660ae77c66e,Недействующее,NaN,Постоянное,Permanent,Нижегородская область,52.0,Приволжский федеральный округ,ПФО,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
692567,1.0,ffffdaa5-0b87-4774-bc2a-f660ae77c66e,Недействующее,NaN,Постоянное,Permanent,Нижегородская область,52.0,Приволжский федеральный округ,ПФО,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
692568,1.0,ffffdaa5-0b87-4774-bc2a-f660ae77c66e,Недействующее,NaN,Постоянное,Permanent,Нижегородская область,52.0,Приволжский федеральный округ,ПФО,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
692569,1.0,ffffdaa5-0b87-4774-bc2a-f660ae77c66e,Недействующее,NaN,Постоянное,Permanent,Нижегородская область,52.0,Приволжский федеральный округ,ПФО,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
692570,1.0,ffffdaa5-0b87-4774-bc2a-f660ae77c66e,Недействующее,NaN,Постоянное,Permanent,Нижегородская область,52.0,Приволжский федеральный округ,ПФО,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [40]:
edu_df.info(max_cols=edu_df.shape[1])

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 692571 entries, 0 to 692570
Data columns (total 138 columns):
 #    Column                            Non-Null Count   Dtype
---   ------                            --------------   -----
 0    IsFederal                         357471 non-null  float64
 1    Id                                692571 non-null  object
 2    StatusName                        692571 non-null  object
 3    StatusCode                        245633 non-null  object
 4    TypeName                          692571 non-null  object
 5    TypeCode                          692571 non-null  object
 6    RegionName                        688239 non-null  object
 7    RegionCode                        688239 non-null  float64
 8    FederalDistrictName               686951 non-null  object
 9    FederalDistrictShortName          686951 non-null  object
 10   FederalDistrictCode               686951 non-null  object
 11   RegNumber                         692454 non-null  object
 12   SerialNumber                      673217 non-null  object
 13   FormNumber                        674280 non-null  object
 14   IssueDate                         692547 non-null  object
 15   EndDate                           682316 non-null  object
 16   ControlOrgan                      675378 non-null  object
 17   PostAddress                       692236 non-null  object
 18   EduOrgFullName                    692298 non-null  object
 19   EduOrgShortName                   327305 non-null  object
 20   EduOrgINN                         681245 non-null  object
 21   EduOrgKPP                         323393 non-null  object
 22   EduOrgOGRN                        674187 non-null  object
 23   IndividualEntrepreneurLastName    0 non-null       float64
 24   IndividualEntrepreneurFirstName   0 non-null       float64
 25   IndividualEntrepreneurMiddleName  0 non-null       float64
 26   IndividualEntrepreneurAddress     0 non-null       float64
 27   IndividualEntrepreneurEGRIP       0 non-null       float64
 28   IndividualEntrepreneurINN         0 non-null       float64
 29   Id2                               692530 non-null  object
 30   FullName                          692500 non-null  object
 31   Id Рекомендательной системы       1 non-null       object
 32   ShortName                         331524 non-null  object
 33   HeadEduOrgId                      9649 non-null    object
 34   IsBranch                          383357 non-null  float64
 35   PostAddress3                      685631 non-null  object
 36   Phone                             677650 non-null  object
 37   Fax                               636476 non-null  object
 38   Email                             674403 non-null  object
 39   WebSite                           451060 non-null  object
 40   OGRN                              674491 non-null  object
 41   INN                               681322 non-null  object
 42   KPP                               325115 non-null  object
 43   HeadPost                          622907 non-null  object
 44   HeadName                          680100 non-null  object
 45   FormName                          357471 non-null  object
 46   FormCode                          177125 non-null  float64
 47   KindName                          370393 non-null  object
 48   KindCode                          0 non-null       float64
 49   TypeName4                         370137 non-null  object
 50   TypeCode5                         53534 non-null   object
 51   RegionName6                       688200 non-null  object
 52   RegionCode7                       688200 non-null  float64
 53   FederalDistrictCode8              686912 non-null  object
 54   FederalDistrictShortName9         686912 non-null  object
 55   FederalDistrictName10             686912 non-null  object
 56   IndividualEntrepreneur            0 non-null       float64
 57   Id11                              574461 non-null  object
 58   StatusName12                      574428 non-null  object
 59   StatusCode13                      39734 non-null   object
 60   Number                            573970 non-null  object
 61   SerialNumber14                    359722 non-null  object
 62   FormNumber15                      351248 non-null  object
 63   IssueDate16                       573729 non-null  object
 64   IsForBranch                       574461 non-null  float64
 65   Note                              6343 non-null    object
 66   EduOrgFullName17                  503392 non-null  object
 67   EduOrgShortName18                 309943 non-null  object
 68   EduOrgAddress                     353346 non-null  object
 69   EduOrgKPP19                       302503 non-null  object
 70   Id20                              570020 non-null  object
 71   FullName21                        567405 non-null  object
 72   ShortName22                       310951 non-null  object
 73   HeadEduOrgId23                    66891 non-null   object
 74   IsBranch24                        361903 non-null  float64
 75   PostAddress25                     548780 non-null  object
 76   Phone26                           545310 non-null  object
 77   Fax27                             513266 non-null  object
 78   Email28                           542718 non-null  object
 79   WebSite29                         315498 non-null  object
 80   OGRN30                            486702 non-null  object
 81   INN31                             492619 non-null  object
 82   KPP32                             303363 non-null  object
 83   HeadPost33                        471895 non-null  object
 84   HeadName34                        543594 non-null  object
 85   FormName35                        287245 non-null  object
 86   FormCode36                        146091 non-null  float64
 87   KindName37                        298373 non-null  object
 88   KindCode38                        0 non-null       float64
 89   TypeName39                        298167 non-null  object
 90   TypeCode40                        44344 non-null   object
 91   RegionName41                      499390 non-null  object
 92   RegionCode42                      499390 non-null  float64
 93   FederalDistrictCode43             498248 non-null  object
 94   FederalDistrictShortName44        498248 non-null  object
 95   FederalDistrictName45             498248 non-null  object
 96   IndividualEntrepreneur46          0 non-null       float64
 97   Id47                              566263 non-null  object
 98   TypeName48                        307680 non-null  object
 99   TypeCode49                        0 non-null       float64
 100  KindName50                        0 non-null       float64
 101  KindCode51                        0 non-null       float64
 102  EduLevelName                      564148 non-null  object
 103  EdulevelShortName                 95529 non-null   object
 104  EduLevelCode                      530891 non-null  object
 105  EduSubLevelName                   0 non-null       float64
 106  EduSubLevelCode                   0 non-null       float64
 107  ProgrammName                      354342 non-null  object
 108  ProgrammCode                      325785 non-null  object
 109  OKSOCode                          130680 non-null  object
 110  UGSName                           337816 non-null  object
 111  UGSCode                           304899 non-null  object
 112  EduNormativePeriod                72963 non-null   object
 113  Qualification                     191628 non-null  object
 114  IsAccredited                      354355 non-null  float64
 115  IsCanceled                        566263 non-null  float64
 116  IsSuspended                       566263 non-null  float64
 117  Id52                              7981 non-null    object
 118  DecisionTypeName                  6744 non-null    object
 119  DecisionTypeCode                  278 non-null     object
 120  OrderDocumentNumber               49803 non-null   object
 121  OrderDocumentKind                 49805 non-null   object
 122  DecisionDate                      49802 non-null   object
 123  AdditionalInfo                    0 non-null       float64
 124  StartedSupplementId               30687 non-null   object
 125  StartedSupplementNumber           30754 non-null   object
 126  StartedSupplementSerialNumber     28989 non-null   object
 127  StartedSupplementFormNumber       28908 non-null   object
 128  StartedSupplementIssueDate        30779 non-null   object
 129  StoppedSupplementId               9 non-null       object
 130  StoppedSupplementNumber           9 non-null       float64
 131  StoppedSupplementSerialNumber     9 non-null       object
 132  StoppedSupplementFormNumber       5 non-null       object
 133  StoppedSupplementIssueDate        9 non-null       object
 134  OldRegNumber                      5458 non-null    object
 135  OldSerialNumber                   5444 non-null    object
 136  OldFormNumber                     5444 non-null    object
 137  OldIssueDate                      5460 non-null    object
dtypes: float64(29), object(109)
memory usage: 729.2+ MB

In [213]:
edu_columns_df = edu_df.agg(['count','nunique']).T.reset_index()
edu_columns_df

                          index   count  nunique
0                     IsFederal  357471        2
1                            Id  692571    92016
2                    StatusName  692571        5
3                    StatusCode  245633        1
4                      TypeName  692571        3
..                          ...     ...      ...
133  StoppedSupplementIssueDate       9        9
134                OldRegNumber    5458     2104
135             OldSerialNumber    5444        9
136               OldFormNumber    5444     2339
137                OldIssueDate    5460     2968

[138 rows x 3 columns]

In [215]:
edu_columns_df.to_csv('edu_columns.csv', sep = ',', index=False)

In [216]:
edu_df['StatusName'].unique()

array(['Недействующее', 'Действующее', 'Прекращено', 'Лишен аккредитации',
       'Приостановлено'], dtype=object)

In [217]:
edu_df['StatusName12'].unique()

array(['Недействующее', nan, 'Действующее', 'Прекращено',
       'Приостановлено в отношении отдельных уровней образования, укрупненных групп специальностей и направлений подготовки',
       'Возобновлено',
       'Лишение в отношении отдельных уровней образования, укрупненных групп специальностей и направлений подготовки',
       'Лишен аккредитации', 'Приостановлено'], dtype=object)

In [218]:
edu_df[(edu_df['StatusName'] != edu_df['StatusName12'])][['StatusName','StatusName12']]

           StatusName StatusName12
3       Недействующее          NaN
6         Действующее          NaN
7         Действующее          NaN
10        Действующее          NaN
14      Недействующее          NaN
...               ...          ...
692524  Недействующее  Действующее
692525  Недействующее          NaN
692529    Действующее          NaN
692533    Действующее          NaN
692570  Недействующее          NaN

[143176 rows x 2 columns]

In [238]:
columns = ['FullName','ShortName','PostAddress','ProgrammName','UGSName']
high_edu_df = edu_df[(
    (edu_df['EduLevelName'].str.contains('^(ВО -|Высшее) ', na=False, regex=True)) &
    (edu_df['StatusName12'].isin(['Действующее','Возобновлено'])))][columns]

/tmp/ipykernel_358639/3613693267.py:3: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  (edu_df['EduLevelName'].str.contains('^(ВО -|Высшее) ', na=False, regex=True)) &

In [239]:
high_edu_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 34630 entries, 98 to 690816
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   FullName      34630 non-null  object
 1   ShortName     34481 non-null  object
 2   PostAddress   34626 non-null  object
 3   ProgrammName  34618 non-null  object
 4   UGSName       34618 non-null  object
dtypes: object(5)
memory usage: 1.6+ MB

In [240]:
high_edu_df.nunique()

FullName        1139
ShortName       1117
PostAddress     1151
ProgrammName     592
UGSName           92
dtype: int64

In [51]:
#.str.replace('\(.*\)','', regex=True).unique()

array([nan], dtype=object)

In [52]:
#high_edu_df['UGSName'] = high_edu_df['UGSName'].fillna(high_edu_df['ProgrammName'].str.replace('\(.*\)','', regex=True))

In [53]:
#high_edu_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 34630 entries, 98 to 690816
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   FullName      34630 non-null  object
 1   ShortName     34481 non-null  object
 2   PostAddress   34626 non-null  object
 3   ProgrammName  34618 non-null  object
 4   UGSName       34618 non-null  object
dtypes: object(5)
memory usage: 1.6+ MB

In [241]:
high_edu_df.dropna(subset = ['ProgrammName'], inplace=True)

In [242]:
high_edu_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 34618 entries, 98 to 690816
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   FullName      34618 non-null  object
 1   ShortName     34481 non-null  object
 2   PostAddress   34618 non-null  object
 3   ProgrammName  34618 non-null  object
 4   UGSName       34618 non-null  object
dtypes: object(5)
memory usage: 1.6+ MB

In [243]:
high_edu_df.nunique()

FullName        1134
ShortName       1117
PostAddress     1147
ProgrammName     592
UGSName           92
dtype: int64

In [244]:
high_edu_df['UGSName'].unique()

array(['Техника и технологии строительства',
       'Электроника, радиотехника и системы связи',
       'Электро- и теплоэнергетика',
       'Техника и технологии наземного транспорта',
       'Науки о здоровье и профилактическая медицина',
       'Биологические науки', 'Химические технологии',
       'Экономика и управление', 'История и археология',
       'Физико-технические науки и технологии',
       'Культуроведение и социокультурные проекты',
       'Политические науки и регионоведение',
       'Образование и педагогические науки', 'Психологические науки',
       'Информатика и вычислительная техника', 'Искусствознание',
       'Физическая культура и спорт', 'Управление в технических системах',
       'Информационная безопасность',
       'Средства массовой информации и информационно-библиотечное дело',
       'Языкознание и литературоведение',
       'Изобразительное и прикладные виды искусств',
       'Физика и астрономия', 'Технологии материалов',
       'Социология и социальная работа', 'Машиностроение',
       'Математика и механика', 'Сервис и туризм',
       'Компьютерные и информационные науки', 'Архитектура',
       'Философия, этика и религиоведение',
       'Техносферная безопасность и природообустройство',
       'Клиническая медицина', 'Здравоохранение', 'Гуманитарные науки',
       'Юриспруденция', 'Сфера обслуживания',
       'Физико-математические науки', 'Фундаментальная медицина',
       'Фармация', 'Химия', 'Культура и искусство', 'Естественные науки',
       'Экранные искусства', 'Науки о Земле',
       'Сценические искусства и литературное творчество',
       'Музыкальное искусство', 'Сельскохозяйственные науки',
       'Технические науки', 'Теология', 'Нанотехнологии и наноматериалы',
       'Сельское, лесное и рыбное хозяйство', 'Ветеринария и зоотехния',
       'Оружие и системы вооружения', 'Военное управление',
       'Промышленная экология и биотехнологии',
       'Прикладная геология, горное дело, нефтегазовое дело и геодезия',
       'Технологии легкой промышленности', 'Науки о земле',
       'Обеспечение государственной безопасности',
       'Востоковедение и африканистика',
       'Фотоника, приборостроение, оптические и биотехнические системы и технологии',
       'Авиационная и ракетно-космическая техника',
       'Ядерная энергетика и технологии',
       'Техника и технологии кораблестроения и водного транспорта',
       'Аэронавигация и эксплуатация авиационной и ракетно-космической техники',
       'Энергетика, энергетическое машиностроение и электротехника',
       'Сестринское дело',
       'Информационная безопасность и противодействие техническим разведкам',
       'Исторические науки и археология', 'Военное образование',
       'Сельское и рыбное хозяйство', 'Транспортные средства',
       'Геодезия и землеустройство',
       'Безопасность жизнедеятельности, природообустройство и защита окружающей среды',
       'Архитектура и строительство', 'Образование и педагогика',
       'Металлургия, машиностроение и материалообработка',
       'Автоматика и управление',
       'Электронная техника, радиотехника и связь', 'Социальные науки',
       'Технология продовольственных продуктов и потребительских товаров',
       'Воспроизводство и переработка лесных ресурсов',
       'Юридические науки', 'Педагогические науки',
       'Социологические науки', 'Экономические науки', 'Политология',
       'Филологические науки', 'Химические науки',
       'Документальная информация', 'Философские науки'], dtype=object)

In [245]:
for col in list(high_edu_df.columns):
    high_edu_df[col] = high_edu_df[col].str.replace(r'\s{2,}', ' ',regex=True).str.strip()

In [246]:
high_edu_df.nunique()

FullName        1134
ShortName       1117
PostAddress     1145
ProgrammName     592
UGSName           92
dtype: int64

In [247]:
high_edu_df.drop_duplicates(inplace=True)
high_edu_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 22069 entries, 98 to 690815
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   FullName      22069 non-null  object
 1   ShortName     21940 non-null  object
 2   PostAddress   22069 non-null  object
 3   ProgrammName  22069 non-null  object
 4   UGSName       22069 non-null  object
dtypes: object(5)
memory usage: 1.0+ MB

In [248]:
high_edu_df['FullName'].unique()

array(['федеральное государственное казенное военное образовательное учреждение высшего образования «Тюменское высшее военно-инженерное командное училище имени маршала инженерных войск А.И.Прошлякова» Министерства обороны Российской Федерации',
       'федеральное государственное бюджетное образовательное учреждение высшего образования «Череповецкий государственный университет»',
       'Федеральное государственное бюджетное образовательное учреждение дополнительного профессионального образования «Институт повышения квалификации Федерального медико-биологического агентства»',
       ...,
       'федеральное государственное автономное образовательное учреждение высшего образования «Национальный исследовательский университет «Московский институт электронной техники»',
       'Федеральное государственное бюджетное учреждение науки Институт физиологии растений им. К.А. Тимирязева Российской академии наук',
       'федеральное государственное бюджетное образовательное учреждение инклюзивного высшего образования «Московский государственный гуманитарно-экономический университет»'],
      dtype=object)

In [249]:
maxColumnLenghts = []
for col in range(len(high_edu_df.columns)):
    maxColumnLenghts.append(max(high_edu_df.iloc[:,col].astype(str).apply(len)))
print('Max Column Lengths ', maxColumnLenghts)

Max Column Lengths  [297, 302, 151, 254, 77]

In [251]:
high_edu_df.reset_index(inplace=True, drop=True)

In [282]:
city_df = high_edu_df[['PostAddress']].drop_duplicates()
city_df['PostAddress'] = city_df['PostAddress'] + ","
city_df.reset_index(inplace=True, drop=True)
city_df

                                            PostAddress
0         625001, г. Тюмень, улица Льва Толстого, д. 1,
1     162600, Вологодская область, г. Череповец, про...
2     125371, Российская Федерация, город Москва, Во...
3     460000, Российская Федерация, Оренбургская обл...
4     Республика Армения, г. Ереван, ул. Овсепа Эмин...
...                                                 ...
1140  628012, Тюменская область, Ханты-Мансийский ав...
1141  124498, г. Москва, г. Зеленоград, площадь Шоки...
1142  Российская Федерация, 127276, г. Москва, ул. Б...
1143  Российская Федерация, 357600, Ставропольский к...
1144    107150, г. Москва, ул. Лосиноостровская, д. 49,

[1145 rows x 1 columns]

In [128]:
#city_df.drop(columns=['postcode','city','city1','city2','city3'], inplace=True)

In [283]:
city_df['postcode'] = city_df['PostAddress'].str.extract(r'(\d{6})', expand=True)

#city_df['city1'] = city_df['PostAddress'].str.replace(' ', '').str.extract(r'г\.(\S*?),')

city_df['city1'] = city_df['PostAddress'].str.replace('- ','-').str.replace(' -','-').str.replace(' Московской области', '').str.extract(r'г\.\s*(.*?),')
city_df['city2'] = city_df['PostAddress'].str.replace(' Челябинской области', '').str.extract(r'\Wгород\s+(.*?),')
city_df['city3'] = city_df['PostAddress'].str.extract(r'гор\.\s*(.*?),')
#city_df['city4'] = city_df['PostAddress'].str.extract(r'с\.\s*(.*?),')

city_df['city'] = city_df['city1']
city_df['city'] = city_df['city'].fillna(city_df['city2'])
city_df['city'] = city_df['city'].fillna(city_df['city3'])

#str.replace('\(.*\)','', regex=True))

In [ ]:
#city_df[(~city_df['city3'].isna())].head(30)

In [284]:
city_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1145 entries, 0 to 1144
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PostAddress  1145 non-null   object
 1   postcode     1127 non-null   object
 2   city1        936 non-null    object
 3   city2        134 non-null    object
 4   city3        2 non-null      object
 5   city         1072 non-null   object
dtypes: object(6)
memory usage: 53.8+ KB

In [285]:
city_df.nunique()

PostAddress    1145
postcode        707
city1           153
city2            60
city3             2
city            163
dtype: int64

In [286]:
city_df[(~city_df['city'].isna())]['city'].unique()

array(['Тюмень', 'Череповец', 'Москва', 'Оренбург', 'Ереван',
       'Санкт-Петербург', 'Кемерово', 'Воронеж', 'Армавир', 'Казань',
       'Кострома', 'Набережные Челны', 'Рязань', 'Йошкар-Ола',
       'Ярославль', 'Киров', 'Архангельск', 'Красноярск', 'Ставрополь',
       'Владимир', 'Владивосток', 'Владикавказ', 'Белгород',
       'Железногорск', 'Брянск', 'Химки', 'Смоленск', 'Калининград',
       'Нижний Новгород', 'Ульяновск', 'Горно-Алтайск', 'Волгоград',
       'Верхняя Пышма', 'Елец', 'Майкоп', 'Альметьевск', 'Новосибирск',
       'Ростов-на-Дону', 'Уфа', 'Барнаул', 'Жуковский', 'Магадан',
       'Магнитогорск', 'Чебоксары', 'Пермь', 'Самара', 'Челябинск',
       'Липецк', 'Тамбов', 'Сургут', 'Томск', 'Екатеринбург', 'Улан-Удэ',
       'Иваново', 'Махачкала', 'Хабаровск', 'Краснодар', 'Пущино',
       'Глазов', 'Сочи', 'Астрахань', 'Чита', 'Грозный', 'Домодедово',
       'Южно-Сахалинск', 'Мурманск', 'Абакан', 'Тверь', 'Ижевск',
       'Симферополь', 'Благовещенск', 'Волжский', 'Саратов',
       'Новокузнецк', 'Якутск', 'Тольятти', 'Нальчик', 'Омск',
       'Ханты-Мансийск', 'Протвино', 'Рыбинск',
       'Петропавловск-Камчатский', 'Кызыл', 'Орел', 'Элиста', 'Голицыно',
       'Княгинино', 'Иркутск', 'Вологда', 'Черноголовка', 'Шадринск',
       'Обнинск', 'Зерноград', 'Новочеркасск', 'Дзержинский', 'Апатиты',
       'Михайловск', 'Великий Новгород', 'Пятигорск', 'Душанбе', 'Пенза',
       'Курск', 'Тула', 'Гатчина', 'Дубна', 'Мытищи', 'Псков', 'Назрань',
       'Донецк', 'Курган', 'Биробиджан', 'Норильск', 'Кировск', 'Бийск',
       'Могилев', 'Великие Луки', 'Пушкин', 'Королев', 'Саранск',
       'Черкесск', 'Магас', 'Макеевка', 'Уссурийск', 'Братск', 'Серпухов',
       'Комсомольск-на-Амуре', 'Чайковский', 'Петрозаводск', 'Саров',
       'Дербент', 'Люберцы', 'Невинномысск', 'Орехово-Зуево', 'Мичуринск',
       'Севастополь', 'Калуга', 'Луганск', 'Сергиев Посад', 'Бишкек',
       'Орёл', 'Коломна', 'Ухта', 'Троицк', 'Ковров', 'Курган-16',
       'Кинель', 'Ессентуки', 'Нижневартовск', 'Обь', 'Ялта', 'Сыктывкар',
       'Таганрог', 'Носибирск', 'Балашиха', 'Анапа', 'Тирасполь',
       'Видное', 'Долгопрудный', 'Ангарск', 'Иннополис', 'Карачаевск',
       'Керчь', 'Новороссийск'], dtype=object)

In [260]:
# city_df[city_df['city2']=='ок']

Empty DataFrame
Columns: [PostAddress, postcode, city1, city2, city3, city]
Index: []

In [181]:
# list(city_df[city_df['city2']=='ок']['PostAddress'])

[]

In [287]:
#list(city_df[(city_df['city1'].isna() & city_df['city2'].isna() & city_df['city3'].isna() & city_df['city4'].isna() & city_df['postcode'].isna())]['PostAddress'])
#list(city_df[(~city_df['city3'].isna())]['PostAddress'])
list(city_df[(city_df['city'].isna() & city_df['postcode'].isna())]['PostAddress'])

['Самарская область, Ставропольский район, Ставропольский лесхоз, Ягодинское лесничество, квартал № 5, оздоровительный комплекс «Алые паруса», корпус № 5,']

In [288]:
city_df.loc[city_df['PostAddress'].str.contains('Алые паруса'),'postcode'] = '445144'

In [289]:
city_df[city_df['PostAddress'].str.contains('Алые паруса')]
# 445144

,PostAddress,postcode,city1,city2,city3,city
988,"Самарская область, Ставропольский район, Ставр...",445144,NaN,NaN,NaN,NaN

In [293]:
city_df['PostAddress'] = city_df['PostAddress'].str.replace(r',$', '',regex=True)

In [294]:
city_df.set_index('PostAddress', inplace=True)
city_df.drop(columns=['city1','city2','city3'], inplace=True)

In [295]:
city_df

                                                   postcode            city
PostAddress
625001, г. Тюмень, улица Льва Толстого, д. 1         625001          Тюмень
162600, Вологодская область, г. Череповец, прос...   162600       Череповец
125371, Российская Федерация, город Москва, Вол...   125371          Москва
460000, Российская Федерация, Оренбургская обла...   460000        Оренбург
Республика Армения, г. Ереван, ул. Овсепа Эмина...      NaN          Ереван
...                                                     ...             ...
628012, Тюменская область, Ханты-Мансийский авт...   628012  Ханты-Мансийск
124498, г. Москва, г. Зеленоград, площадь Шокин...   124498          Москва
Российская Федерация, 127276, г. Москва, ул. Бо...   127276          Москва
Российская Федерация, 357600, Ставропольский кр...   357600       Ессентуки
107150, г. Москва, ул. Лосиноостровская, д. 49       107150          Москва

[1145 rows x 2 columns]

In [298]:
high_edu_df = high_edu_df.join(city_df, on='PostAddress', how='left')
high_edu_df

,FullName,ShortName,PostAddress,ProgrammName,UGSName,postcode,city
0,федеральное государственное казенное военное о...,Тюменское высшее военно-инженерное командное у...,"625001, г. Тюмень, улица Льва Толстого, д. 1",Строительство уникальных зданий и сооружений,Техника и технологии строительства,625001,Тюмень
1,федеральное государственное казенное военное о...,Тюменское высшее военно-инженерное командное у...,"625001, г. Тюмень, улица Льва Толстого, д. 1",Специальные радиотехнические системы,"Электроника, радиотехника и системы связи",625001,Тюмень
2,федеральное государственное казенное военное о...,Тюменское высшее военно-инженерное командное у...,"625001, г. Тюмень, улица Льва Толстого, д. 1",Тепло- и электрообеспечение специальных технич...,Электро- и теплоэнергетика,625001,Тюмень
3,федеральное государственное казенное военное о...,Тюменское высшее военно-инженерное командное у...,"625001, г. Тюмень, улица Льва Толстого, д. 1",Транспортные средства специального назначения,Техника и технологии наземного транспорта,625001,Тюмень
4,федеральное государственное бюджетное образова...,Череповецкий государственный университет,"162600, Вологодская область, г. Череповец, про...",Общественное здравоохранение,Науки о здоровье и профилактическая медицина,162600,Череповец
...,...,...,...,...,...,...,...
22064,федеральное государственное бюджетное образова...,ФГБОУИ ВО «Московский государственный гуманита...,"107150, г. Москва, ул. Лосиноостровская, д. 49",Педагогическое образование,Образование и педагогические науки,107150,Москва
22065,федеральное государственное бюджетное образова...,ФГБОУИ ВО «Московский государственный гуманита...,"107150, г. Москва, ул. Лосиноостровская, д. 49",Психолого-педагогическое образование,Образование и педагогические науки,107150,Москва
22066,федеральное государственное бюджетное образова...,ФГБОУИ ВО «Московский государственный гуманита...,"107150, г. Москва, ул. Лосиноостровская, д. 49",Лингвистика,Языкознание и литературоведение,107150,Москва
22067,федеральное государственное бюджетное образова...,ФГБОУИ ВО «Московский государственный гуманита...,"107150, г. Москва, ул. Лосиноостровская, д. 49",Перевод и переводоведение,Языкознание и литературоведение,107150,Москва
22068,федеральное государственное бюджетное образова...,ФГБОУИ ВО «Московский государственный гуманита...,"107150, г. Москва, ул. Лосиноостровская, д. 49",Социологические науки,Социология и социальная работа,107150,Москва

In [299]:
high_edu_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 22069 entries, 0 to 22068
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   FullName      22069 non-null  object
 1   ShortName     21940 non-null  object
 2   PostAddress   22069 non-null  object
 3   ProgrammName  22069 non-null  object
 4   UGSName       22069 non-null  object
 5   postcode      21665 non-null  object
 6   city          21526 non-null  object
dtypes: object(7)
memory usage: 1.2+ MB

In [328]:
univer_df = high_edu_df[['FullName','postcode','city']].drop_duplicates()
univer_df.sort_values(by=['FullName','postcode','city'])

,FullName,postcode,city
5016,АВТОНОМНАЯ НЕКОММЕРЧЕСКАЯ ОРГАНИЗАЦИЯ ВЫСШЕГО ...,115054,Москва
14032,Автономная некоммерческая образовательная орга...,394033,Воронеж
4048,Автономная некоммерческая образовательная орга...,690091,Владивосток
14070,Автономная некоммерческая образовательная орга...,191187,Санкт-Петербург
12599,Автономная некоммерческая образовательная орга...,394026,Воронеж
...,...,...,...
6936,частное образовательное учреждение высшего обр...,420111,Казань
10329,частное образовательное учреждение высшего обр...,190103,Санкт-Петербург
15273,частное образовательное учреждение высшего обр...,644010,Омск
19017,частное учреждение образовательная организация...,443001,Самара
18726,частное учреждение образовательная организация...,198099,Санкт-Петербург

In [329]:
univer_df = univer_df.groupby('FullName').agg(
    postcode=('postcode', 'last'),
    city=('city', 'last'))
univer_df

                                                   postcode             city
FullName
АВТОНОМНАЯ НЕКОММЕРЧЕСКАЯ ОРГАНИЗАЦИЯ ВЫСШЕГО О...   115054           Москва
Автономная некоммерческая образовательная орган...   394033          Воронеж
Автономная некоммерческая образовательная орган...   690091      Владивосток
Автономная некоммерческая образовательная орган...   191187  Санкт-Петербург
Автономная некоммерческая образовательная орган...   394026          Воронеж
...                                                     ...              ...
частное образовательное учреждение высшего обра...   420111           Казань
частное образовательное учреждение высшего обра...   190103  Санкт-Петербург
частное образовательное учреждение высшего обра...   644010             Омск
частное учреждение образовательная организация ...   443001           Самара
частное учреждение образовательная организация ...   198099  Санкт-Петербург

[1134 rows x 2 columns]

In [330]:
univer_df[univer_df['city'].isna()]

                                                   postcode  city
FullName
Автономная некоммерческая образовательная орган...   143025  None
Автономная некоммерческая организация высшего о...   121357  None
Автономная некоммерческая организация высшего о...   191011  None
Автономная некоммерческая организация высшего о...   197183  None
Автономная некоммерческая организация высшего о...   192012  None
...                                                     ...   ...
федеральное государственное бюджетное образоват...   191186  None
федеральное государственное бюджетное образоват...   119002  None
федеральное государственное бюджетное образоват...   620014  None
федеральное государственное бюджетное учреждени...   600901  None
федеральное государственное бюджетное учреждени...   194021  None

[72 rows x 2 columns]

In [331]:
univer_df.reset_index(inplace=True)

In [333]:
univer_df[univer_df['FullName'].isin(['Частное образовательное учреждение высшего образования «Академия управления и производства»'])]
#univer_df[tuniver_dfmp['FullName'].isin(['Частное образовательное учреждение высшего образования «Русская христианская гуманитарная академия»'])]

                                              FullName postcode    city
498  Частное образовательное учреждение высшего обр...   123007  Москва

In [317]:
#high_edu_df[high_edu_df['FullName'].isin(['Частное образовательное учреждение высшего образования «Академия управления и производства»'])]
high_edu_df[high_edu_df['FullName'].isin(['Частное образовательное учреждение высшего образования «Русская христианская гуманитарная академия»'])]

,FullName,ShortName,PostAddress,ProgrammName,UGSName,postcode,city
18094,Частное образовательное учреждение высшего обр...,ЧОУ «Русская христианская гуманитарная академи...,"191011, Санкт-Петербург, наб. реки Фонтанки, д...",Психология,Психологические науки,191011,NaN
18095,Частное образовательное учреждение высшего обр...,ЧОУ «Русская христианская гуманитарная академи...,"191011, Санкт-Петербург, наб. реки Фонтанки, д...",Филология,Языкознание и литературоведение,191011,NaN
18096,Частное образовательное учреждение высшего обр...,ЧОУ «Русская христианская гуманитарная академи...,"191011, Санкт-Петербург, наб. реки Фонтанки, д...",Философия,"Философия, этика и религиоведение",191011,NaN
18097,Частное образовательное учреждение высшего обр...,ЧОУ «Русская христианская гуманитарная академи...,"191011, Санкт-Петербург, наб. реки Фонтанки, д...",Религиоведение,"Философия, этика и религиоведение",191011,NaN
18098,Частное образовательное учреждение высшего обр...,ЧОУ «Русская христианская гуманитарная академи...,"191011, Санкт-Петербург, наб. реки Фонтанки, д...",Искусства и гуманитарные науки,Искусствознание,191011,NaN
18099,Частное образовательное учреждение высшего обр...,ЧОУ «Русская христианская гуманитарная академи...,"191011, Санкт-Петербург, наб. реки Фонтанки, д...","Философия, этика и религиоведение","Философия, этика и религиоведение",191011,NaN
18100,Частное образовательное учреждение высшего обр...,ЧОУ «Русская христианская гуманитарная академи...,"191011, Санкт-Петербург, наб. реки Фонтанки, д...",Теология,Теология,191011,NaN
20184,Частное образовательное учреждение высшего обр...,ЧОУ «Русская христианская гуманитарная академи...,"191011, г. Санкт-Петербург, набережная реки Фо...",Психология,Психологические науки,191011,Санкт-Петербург
20185,Частное образовательное учреждение высшего обр...,ЧОУ «Русская христианская гуманитарная академи...,"191011, г. Санкт-Петербург, набережная реки Фо...",Филология,Языкознание и литературоведение,191011,Санкт-Петербург
20186,Частное образовательное учреждение высшего обр...,ЧОУ «Русская христианская гуманитарная академи...,"191011, г. Санкт-Петербург, набережная реки Фо...",Философия,"Философия, этика и религиоведение",191011,Санкт-Петербург
20187,Частное образовательное учреждение высшего обр...,ЧОУ «Русская христианская гуманитарная академи...,"191011, г. Санкт-Петербург, набережная реки Фо...",Религиоведение,"Философия, этика и религиоведение",191011,Санкт-Петербург
20188,Частное образовательное учреждение высшего обр...,ЧОУ «Русская христианская гуманитарная академи...,"191011, г. Санкт-Петербург, набережная реки Фо...",Теология,Теология,191011,Санкт-Петербург
20189,Частное образовательное учреждение высшего обр...,ЧОУ «Русская христианская гуманитарная академи...,"191011, г. Санкт-Петербург, набережная реки Фо...",Искусства и гуманитарные науки,Искусствознание,191011,Санкт-Петербург
20190,Частное образовательное учреждение высшего обр...,ЧОУ «Русская христианская гуманитарная академи...,"191011, г. Санкт-Петербург, набережная реки Фо...",Культурология,Культуроведение и социокультурные проекты,191011,Санкт-Петербург
20191,Частное образовательное учреждение высшего обр...,ЧОУ «Русская христианская гуманитарная академи...,"191011, г. Санкт-Петербург, набережная реки Фо...","Философия, этика и религиоведение","Философия, этика и религиоведение",191011,Санкт-Петербург

In [334]:
conn = psycopg2.connect(dbname="h_core", user="h_user", password="AUdZuMOGuP", host="84.201.178.7", port="55432")

In [71]:
with conn.cursor() as curs:
    for i in range(len(high_edu_df)):
        curs.execute('INSERT INTO h_raw_edu (Full_Name, Short_Name, Post_Address, Programm_Name, UGS_Name) VALUES (%s, %s, %s, %s, %s)',
                     (high_edu_df.loc[i,'FullName'],
                      high_edu_df.loc[i,'ShortName'],
                      high_edu_df.loc[i,'PostAddress'],
                      high_edu_df.loc[i,'ProgrammName'],
                      high_edu_df.loc[i,'UGSName']))
        if i % 1000 ==0:
            conn.commit()
            print(i)
    conn.commit()

0
1000
2000
3000
4000
5000
6000
7000
8000
9000
10000
11000
12000
13000
14000
15000
16000
17000
18000
19000
20000
21000
22000

In [336]:
conn.close()

# h_edu_directions

In [481]:
high_edu_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 22069 entries, 0 to 22068
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   FullName      22069 non-null  object
 1   ShortName     21940 non-null  object
 2   PostAddress   22069 non-null  object
 3   ProgrammName  22069 non-null  object
 4   UGSName       22069 non-null  object
 5   postcode      21665 non-null  object
 6   city          21526 non-null  object
dtypes: object(7)
memory usage: 1.2+ MB

In [484]:
directions = list(high_edu_df['UGSName'].unique())

In [489]:
len(directions)

92

In [3]:
embedding_model = SentenceTransformer("paraphrase-multilingual-MiniLM-L12-v2")

In [486]:
embeddings = embedding_model.encode(directions)

In [488]:
embeddings.shape

(92, 384)

In [501]:
#str(embeddings[0])
#','.join(embeddings[0])
vec = '[' + (','.join(map(str, embeddings[0]))) + ']'
vec

'[0.014818062,0.15507291,-0.0496795,-0.01601848,-0.13945751,-0.21684112,-0.21002753,0.18450728,-0.1822346,0.064020306,-0.12507756,0.04620213,0.25460446,-0.19469808,-0.0021316165,0.30306473,-0.08526663,0.051373906,0.15184297,-0.14099512,0.23829055,-0.45287052,0.082919225,-0.36378178,0.21015082,0.08741941,-0.0767306,-0.028509496,0.2873407,-0.2600881,-0.1554396,-0.040924422,0.21924493,0.050886218,0.04712463,0.33915973,0.37105805,-0.0949441,-0.19545816,-0.062854275,-0.2699005,-0.16401184,0.12049014,0.10212083,0.06053189,0.29815546,0.059050467,-0.15230922,-0.19088647,-0.1798452,0.080022775,-0.2019277,-0.080322124,-0.3240916,0.07816026,0.021856574,0.49283442,0.25578073,-0.004271287,-0.07984231,0.29070956,0.012343615,-0.5494548,0.2906653,0.3294614,0.001795475,-0.02161127,0.31317583,-0.10844878,0.13917291,-0.058879852,-0.03065276,-0.12646084,-0.15892366,0.06314466,-0.035408568,0.065291785,0.22263972,0.1439357,-0.14159547,0.15646899,-0.012380638,-0.034086943,0.11248577,0.041984957,0.2518981,-0.07198579,0.20457101,0.20077612,-0.14019714,-0.00050940044,-0.19757418,-0.22792557,-0.1368855,0.39419204,-0.13259967,-0.029521743,-0.25589997,0.1697872,0.86669064,-0.15436049,-0.058326542,-0.13222118,-0.25606695,0.07264036,0.107411824,-0.007580154,0.02239711,-0.08267856,-0.19137697,-0.07836886,0.008017986,-0.41156563,-0.016391838,-0.026496792,-0.12284619,-0.4266725,-0.20768537,0.03601984,0.1408733,-0.1166584,-0.14289878,0.14095211,-0.19088376,-0.0625583,-0.51876885,0.19669707,0.0039028607,-0.111321926,0.018011093,0.096727945,0.20120384,0.027861247,0.03158956,0.15446094,0.18997929,0.2606624,-0.22207011,0.016459292,0.013517471,-0.08973463,0.33728975,0.49172089,-0.10708172,0.180337,0.11536945,0.049989074,-0.024070399,0.16311643,-0.064402856,0.21804969,0.013005444,0.27093682,-0.04139338,0.1768338,-0.0010855591,-0.32060358,-0.07893227,0.121885814,-0.03585921,-0.10582934,0.2755271,-0.08413453,0.032886755,-0.14419404,-0.36761114,-0.21829619,-0.14655516,0.12187477,-0.065979265,0.06859756,0.1596999,0.39260274,-0.18671887,0.2819018,0.03306983,-0.22642113,-0.12572128,-0.06853463,0.31079,0.5464392,-0.026172262,0.17693035,-0.083816424,0.21492921,-0.08408111,0.12458785,0.24497423,-0.0910699,0.19845273,-0.047468744,0.21933362,0.2449961,-0.1589271,-0.13927852,-0.14825264,0.38090163,-0.060802247,-0.04806208,-0.25949994,-0.21827124,-0.0487153,-0.31665057,0.17386484,-0.13463105,0.104770355,0.11731909,-0.116971396,-0.16275953,0.23920922,0.032081258,-0.33754125,0.010342146,0.07136646,0.27395803,-0.019009901,-0.14167166,0.16430537,-0.41366735,-0.006212952,0.12275945,0.08358328,0.18165655,-0.4729033,-0.16771099,0.034019355,-0.21919599,0.072827145,0.07341642,-0.11146559,-0.18696645,-0.51281893,0.18217142,0.29151553,-0.25037882,-0.21712664,-0.13809454,-0.031579006,-0.23642084,-0.12039203,0.06349172,-0.33715767,-0.15213253,0.023417827,0.26679516,-0.12795025,-0.29702464,-0.0758294,0.048775174,0.23383667,-0.6986825,-0.28101993,-0.091941975,0.26071903,-0.22593586,-0.16831969,-0.029522428,0.36232504,-0.056731556,0.103673816,0.5710894,0.055044767,-0.033585224,-0.17621645,0.20706214,-0.0011650877,-0.14431106,0.3062382,-0.1613389,-0.13403428,-0.4329311,-0.05580599,-0.26716396,0.084315196,0.34437132,-0.19061892,0.21799235,-0.5037848,0.20034753,0.21864367,-0.1899961,0.093449235,-0.10910732,0.25538072,0.18522985,-0.08982963,0.3178973,0.09158168,-0.14622745,0.19675522,0.15254605,0.1532222,-0.24852143,0.0811825,0.09550058,0.4407948,0.097104564,-0.021542,-0.46258038,-0.13449664,0.14061067,0.13442378,-0.09978962,-0.08211833,0.071459934,-0.12146253,0.26418623,0.13477366,-0.0952033,0.007877134,-0.004922058,-0.24526335,0.0064258003,-0.26699927,-0.011429682,0.14257383,-0.109535046,0.11764528,0.12083764,-0.5146722,-0.31402475,0.014625466,-0.3081429,-0.32684427,0.034391012,-0.089064404,0.08844768,0.27304575,0.05613208,-0.43288726,-0.16802442,-0.0140619725,0.05529443,0.081361674,-0.0027361533,0.041953035,-0.12834217,0.08426946,-0.26928598,-0.008430316,0.4556639,0.22551669,-0.1340494,0.32399708,-0.029427247,-0.095020786,0.15912238,0.06901383,0.35432312,-0.07595711,-0.09921266,0.043422632,-0.10888361,0.0016569203,0.11668541,0.04554642,0.16187482,-0.13139252,-0.08003201,-0.043622784,0.11813574,0.03931846,-0.07259005,0.3222751,0.13239339,0.16358988,-0.4605575,0.15149018,-0.25789186,-0.020421445,0.09854966,0.27247173,-0.06885885,0.26015,0.2491388,0.24689496,-0.052241188,-0.119426504,0.116810426,0.024413573,-0.24941175,-0.08812446,0.31756398,0.21785818]'

In [506]:
conn = psycopg2.connect(dbname="h_core", user="h_user", password="AUdZuMOGuP", host="84.201.178.7", port="55432")

In [507]:
with conn.cursor() as curs:
    for i in range(len(directions)):
        curs.execute('INSERT INTO h_edu_direction (value, embedding) VALUES (%s, %s)', (directions[i], '[' + (','.join(map(str, embeddings[i]))) + ']'))
    conn.commit()

In [508]:
conn.close()

# coordinates by city

In [339]:
towns_df = pd.read_csv('https://raw.githubusercontent.com/epogrebnyak/ru-cities/main/assets/towns.csv', delimiter = ',', usecols=["city", "lat", "lon"])
towns_df

            city        lat        lon
0         Алейск  52.492251  82.779361
1        Барнаул  53.347997  83.779806
2     Белокуриха  51.996152  84.983960
3          Бийск  52.539386  85.213845
4         Горняк  50.997962  81.464336
...          ...        ...        ...
1112      Ростов  57.205132  39.437862
1113     Рыбинск  58.048550  38.858412
1114      Тутаев  57.867499  39.536963
1115       Углич  57.522425  38.302004
1116   Ярославль  57.621548  39.897741

[1117 rows x 3 columns]

In [340]:
univer_df['city'].nunique()

163

In [343]:
cities = list(univer_df['city'].unique())

In [344]:
towns_df[towns_df['city'].isin(cities)].count()

city    157
lat     157
lon     157
dtype: int64

In [417]:
coords4towns_df = towns_df[towns_df['city'].isin(cities)]

In [418]:
coords4towns_df.rename(columns={'lat':'latitude','lon':'longitude'}, inplace=True)
coords4towns_df.set_index('city', inplace=True)

/tmp/ipykernel_358639/2761677130.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  coords4towns_df.rename(columns={'lat':'latitude','lon':'longitude'}, inplace=True)

In [419]:
coords4towns_df

               latitude   longitude
city
Барнаул       53.347997   83.779806
Бийск         52.539386   85.213845
Благовещенск  50.290659  127.527198
Архангельск   64.539429   40.516961
Астрахань     46.365565   48.055924
...                 ...         ...
Челябинск     55.160262   61.400808
Грозный       43.318014   45.698291
Чебоксары     56.143830   47.248978
Рыбинск       58.048550   38.858412
Ярославль     57.621548   39.897741

[157 rows x 2 columns]

In [422]:
univer_df = univer_df.join(coords4towns_df, on='city', how='left')

In [423]:
univer_df

,FullName,postcode,city,latitude,longitude
0,АВТОНОМНАЯ НЕКОММЕРЧЕСКАЯ ОРГАНИЗАЦИЯ ВЫСШЕГО ...,115054,Москва,55.754047,37.620405
1,Автономная некоммерческая образовательная орга...,394033,Воронеж,51.659333,39.196923
2,Автономная некоммерческая образовательная орга...,690091,Владивосток,43.116490,131.882394
3,Автономная некоммерческая образовательная орга...,191187,Санкт-Петербург,59.939131,30.315900
4,Автономная некоммерческая образовательная орга...,394026,Воронеж,51.659333,39.196923
...,...,...,...,...,...
1129,частное образовательное учреждение высшего обр...,420111,Казань,55.794358,49.111497
1130,частное образовательное учреждение высшего обр...,190103,Санкт-Петербург,59.939131,30.315900
1131,частное образовательное учреждение высшего обр...,644010,Омск,54.984857,73.367452
1132,частное учреждение образовательная организация...,443001,Самара,53.195031,50.106952
1133,частное учреждение образовательная организация...,198099,Санкт-Петербург,59.939131,30.315900

In [424]:
univer_df[univer_df['latitude'].isna()]

,FullName,postcode,city,latitude,longitude
6,Автономная некоммерческая образовательная орга...,143025,None,NaN,NaN
19,Автономная некоммерческая организация высшего ...,121357,None,NaN,NaN
23,Автономная некоммерческая организация высшего ...,191011,None,NaN,NaN
31,Автономная некоммерческая организация высшего ...,197183,None,NaN,NaN
35,Автономная некоммерческая организация высшего ...,192012,None,NaN,NaN
...,...,...,...,...,...
1004,федеральное государственное бюджетное учрежден...,196603,Пушкин,NaN,NaN
1035,федеральное государственное бюджетное учрежден...,600901,None,NaN,NaN
1038,федеральное государственное бюджетное учрежден...,194021,None,NaN,NaN
1042,федеральное государственное казенное военное о...,302034,Орёл,NaN,NaN
1086,федеральное государственное казенное образоват...,640016,Курган-16,NaN,NaN

In [425]:
univer_df[univer_df['latitude'].isna()]['postcode'].unique()

array(['143025', '121357', '191011', '197183', '192012', None, '196605',
       '125499', '192242', '192238', '301000', '630559', '142279',
       '664520', '141142', '143050', '140143', '397463', '346735',
       '601125', '198035', '140032', '190121', '117279', '678671',
       '194044', '192019', '123007', '117036', '191186', '119017',
       '620219', '143030', '119991', '152020', '199034', '620014',
       '117342', '125412', '644033', '369167', '630090', '196158',
       '197110', '191025', '109439', '191002', '720000', '212005',
       '734025', '400066', '445144', '111024', '194064', '141435',
       '141261', '308503', '243365', '140155', '346493', '664038',
       '156530', '641300', '302019', '302028', '121165', '191028',
       '141221', '196601', '119002', '196603', '600901', '194021',
       '302034', '640016'], dtype=object)

# coordinates by postcode

In [359]:
POST_SERVICE_URL = 'https://почта.ru.com/{}'

In [426]:
#post_codes = list(univer_df['postcode'].unique())[:2]
#post_codes = list(univer_df['postcode'].unique())
post_codes = list(univer_df[univer_df['latitude'].isna()]['postcode'].unique())

len(post_codes)

75

In [427]:
post_codes[0]

'143025'

In [428]:
print(POST_SERVICE_URL.format(post_codes[0]))

https://почта.ru.com/143025

In [429]:
delay_ = 6
post_codes_df = pd.DataFrame(columns = ['postcode','latitude', 'longitude'])
for cnt, item in enumerate(post_codes):
    print('cnt=', cnt)
    while 1:
        time.sleep(delay_)
        response = requests.request('GET',POST_SERVICE_URL.format(item))
        resp_html = response.text
        if response.status_code == 429:
            delay_ += 1
            print('cnt=', cnt, ' new delay=', delay_)
        else:
            break
    if response.status_code == 200:
        coords_txt = re.search('maps-yandex\?(\S*?)"', resp_html).group(0)[12:][:-1].split('&')
        coords = [x.split('=')[1] for x in coords_txt] # широта, долгота
        post_codes_df.loc[len(post_codes_df)] = [item, coords[0], coords[1]]
    else:
        print('cnt=', cnt, ' postcode=', item,' delay=', delay_)

cnt= 0
cnt= 1
cnt= 2
cnt= 3
cnt= 4
cnt= 5
cnt= 5  postcode= None  delay= 6
cnt= 6
cnt= 7
cnt= 8
cnt= 9
cnt= 10
cnt= 11
cnt= 12
cnt= 13
cnt= 14
cnt= 15
cnt= 16
cnt= 17
cnt= 18
cnt= 19
cnt= 20
cnt= 21
cnt= 22
cnt= 23
cnt= 24
cnt= 25
cnt= 26
cnt= 27
cnt= 28
cnt= 29
cnt= 30
cnt= 31
cnt= 31  postcode= 620219  delay= 6
cnt= 32
cnt= 33
cnt= 34
cnt= 35
cnt= 36
cnt= 37
cnt= 38
cnt= 39
cnt= 40
cnt= 41
cnt= 42
cnt= 43
cnt= 44
cnt= 45
cnt= 46
cnt= 47
cnt= 47  postcode= 720000  delay= 6
cnt= 48
cnt= 48  postcode= 212005  delay= 6
cnt= 49
cnt= 49  postcode= 734025  delay= 6
cnt= 50
cnt= 51
cnt= 52
cnt= 53
cnt= 54
cnt= 55
cnt= 56
cnt= 57
cnt= 58
cnt= 59
cnt= 60
cnt= 61
cnt= 62
cnt= 63
cnt= 64
cnt= 65
cnt= 66
cnt= 67
cnt= 68
cnt= 69
cnt= 70
cnt= 71
cnt= 72
cnt= 73
cnt= 74

In [431]:
post_codes_df.set_index('postcode', inplace=True)

In [435]:
univer_df = univer_df.join(post_codes_df, on='postcode', how='left', rsuffix='_1')

In [436]:
univer_df

,FullName,postcode,city,latitude,longitude,latitude_1,longitude_1
0,АВТОНОМНАЯ НЕКОММЕРЧЕСКАЯ ОРГАНИЗАЦИЯ ВЫСШЕГО ...,115054,Москва,55.754047,37.620405,NaN,NaN
1,Автономная некоммерческая образовательная орга...,394033,Воронеж,51.659333,39.196923,NaN,NaN
2,Автономная некоммерческая образовательная орга...,690091,Владивосток,43.116490,131.882394,NaN,NaN
3,Автономная некоммерческая образовательная орга...,191187,Санкт-Петербург,59.939131,30.315900,NaN,NaN
4,Автономная некоммерческая образовательная орга...,394026,Воронеж,51.659333,39.196923,NaN,NaN
...,...,...,...,...,...,...,...
1129,частное образовательное учреждение высшего обр...,420111,Казань,55.794358,49.111497,NaN,NaN
1130,частное образовательное учреждение высшего обр...,190103,Санкт-Петербург,59.939131,30.315900,NaN,NaN
1131,частное образовательное учреждение высшего обр...,644010,Омск,54.984857,73.367452,NaN,NaN
1132,частное учреждение образовательная организация...,443001,Самара,53.195031,50.106952,NaN,NaN
1133,частное учреждение образовательная организация...,198099,Санкт-Петербург,59.939131,30.315900,NaN,NaN

In [442]:
univer_df = univer_df.astype({'latitude_1':'float','longitude_1':'float'})

In [447]:
univer_df['latitude'] = univer_df['latitude'].fillna(univer_df['latitude_1'])
univer_df['longitude'] = univer_df['longitude'].fillna(univer_df['longitude_1'])

In [452]:
univer_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1146 entries, 0 to 1133
Data columns (total 5 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   FullName   1146 non-null   object
 1   postcode   1129 non-null   object
 2   city       1074 non-null   object
 3   latitude   1136 non-null   float64
 4   longitude  1136 non-null   float64
dtypes: float64(2), object(3)
memory usage: 53.7+ KB

In [451]:
univer_df.drop(columns=['latitude_1','longitude_1'], inplace=True)

In [460]:
univer_df.reset_index(inplace=True, drop=True)

In [461]:
univer_df[univer_df['latitude'].isna()]

Empty DataFrame
Columns: [FullName, postcode, city, latitude, longitude]
Index: []

In [454]:
univer_df.dropna(subset = ['latitude'], inplace=True)

In [476]:
conn = psycopg2.connect(dbname="h_core", user="h_user", password="AUdZuMOGuP", host="84.201.178.7", port="55432")

In [469]:
with conn.cursor() as curs:
    for i in range(len(univer_df)):
        curs.execute('INSERT INTO h_edu_universities (full_name, postcode, city, latitude, longitude) VALUES (%s, %s, %s, %s, %s)',
                     (univer_df.loc[i,'FullName'],
                      univer_df.loc[i,'postcode'],
                      univer_df.loc[i,'city'],
                      univer_df.loc[i,'latitude'],
                      univer_df.loc[i,'longitude']))
        if i % 1000 ==0:
            conn.commit()
            print(i)
    conn.commit()

0
1000

In [477]:
with conn.cursor() as curs:
    curs.execute('insert into h_edu_direct2univ (direction_id, university_id) ' +
                 'select distinct d.direction_id, u.university_id ' +
                 'from h_raw_edu r, h_edu_direction d, h_edu_universities u ' +
                 'where d.value = r.ugs_name and u.full_name = r.full_name')
conn.commit()

In [478]:
conn.close()

# test selects with embedding conditions

In [4]:
vk_faculty = 'Факультет биоинженерии и биоинформатики'

coords = (53.507852, 49.420411)

In [ ]:
select_query = 'select * from (select embedding <-> %s as cos, d.direction_id, d.value from h_edu_direction d ORDER BY d.embedding <-> %s limit 2) d'

In [571]:
select_query = ('select * from ' + 
                ' (select cos, faculty, full_name, city, dist, ' +
                '     row_number() over (partition by faculty order by dist) univ_dist_rank ' +
                '     from ' +
                '   (select distinct d.cos, d.faculty, u.full_name, u.city, ' +
                '     get_haversine_distance(u.latitude, u.longitude, %s, %s) dist ' +
                '    from ' +
                '     (select d.direction_id, d.value as faculty, '
                '       embedding <-> %s as cos '
                '      from h_edu_direction d order by d.embedding <-> %s limit 2) d, ' +
                '     h_edu_direct2univ d2u, h_edu_universities u ' +
                '    where d2u.direction_id = d.direction_id and u.university_id = d2u.university_id) u) u ' +
                'where univ_dist_rank < 10 ' +
                'order by faculty, univ_dist_rank, full_name')

In [6]:
embeddings4select = embedding_model.encode(vk_faculty)

In [7]:
embeddings4select = '[' + (','.join(map(str, embeddings4select))) + ']'

In [9]:
conn = psycopg2.connect(dbname="h_core", user="h_user", password="AUdZuMOGuP", host="84.201.178.7", port="55432")

In [575]:
with conn.cursor() as curs:
    curs.execute(select_query,(coords[0], coords[1], embeddings4select,embeddings4select))
    rs = curs.fetchall()

In [12]:
select_query = 'select embedding <-> %s as cos, * from h_additional_data order by embedding <-> %s limit 9'

In [13]:
with conn.cursor() as curs:
    curs.execute(select_query,(embeddings4select,embeddings4select))
    rs = curs.fetchall()

In [14]:
rs

[(0.7847840295117406,
  '3ad7e6fb-7a43-4b20-9662-fe5721d43542',
  datetime.datetime(2023, 12, 10, 9, 29, 54, 966043),
  datetime.datetime(2023, 12, 10, 9, 29, 54, 966045),
  'be05f3b1-83ad-431a-89a2-027b002a2a10',
  '0707cbb7-bd81-4d68-89b6-f976c6b18d97',
  '[0.049131718,0.35103276,-0.028960692,-0.0022693933,-0.13416173,-0.2506562,-0.17928338,0.29163027,-0.058073618,0.22603568,0.11569243,-0.46069965,-0.19010292,0.29466888,-0.16147867,-0.14397892,-0.1609763,0.05348116,0.22194193,-0.046665143,0.19036303,0.097731374,0.27300388,-0.050807204,-0.044407174,-0.040840067,-0.32035193,-0.09240401,-0.050059866,-0.22090918,0.21913697,0.023545286,0.21290702,-0.006368208,-0.023853099,0.29873568,-0.15738061,0.14523008,0.0319321,0.2660536,-0.042062473,-0.15821715,0.13299641,0.20994815,-0.058819022,-0.03333393,0.00718725,-0.14683689,-0.015347939,-0.43625528,-0.09787679,-0.26458797,-0.1789081,-0.21198282,0.12159367,0.0038452053,0.22935809,-0.121762566,-0.11999014,-0.023482295,0.2787278,0.11213771,-0.28440866,0.38646463,-0.012182363,-0.24303366,0.14157614,0.21997476,0.20341347,-0.2551333,0.0047253524,-0.34495455,0.15833063,0.18079329,0.23058563,0.29404703,0.09404295,0.07171281,0.3413265,-0.16542046,0.16377258,-0.050976563,0.09541452,0.1134663,-0.012614026,0.3282774,-0.037958745,0.0350683,0.07130668,0.029522149,0.14750203,-0.36154273,0.06758494,-0.27031288,-0.031106167,0.10105356,-0.09349152,-0.2084377,0.19600798,0.3869746,-0.10618354,-0.030814769,-0.1971054,0.0034455578,-0.03380608,-0.24113108,-0.040578183,-0.16127966,0.2901829,0.19577028,0.034016058,0.104884945,-0.16864066,0.020955663,0.1348341,0.30001503,-0.04945439,-0.11357508,0.20522435,0.20948154,-0.23159356,-0.20676263,0.17724475,-0.13457209,0.20896286,-0.02159567,0.02270385,0.07526981,0.27384394,0.07051964,0.29573333,0.077668875,-0.06726345,0.028814193,-0.04886661,-0.15576982,0.14401002,-0.012942382,-0.08554623,0.12812139,0.03167138,0.08216534,-0.14187147,0.0047800625,-0.2975562,0.1319709,-0.17575906,-0.045325123,0.0049573677,0.013032882,0.054050986,-0.03244722,0.115432456,-0.059883706,0.10780641,-0.023047097,0.20504218,0.09378567,0.01738298,-0.07568426,-0.0901368,0.09366504,0.20594747,0.07554436,-0.0055760057,-0.2530361,0.009814192,-0.26540643,-0.07990834,0.23478025,0.21786143,-0.3127066,0.31824684,0.039226227,0.05254822,0.020125536,0.10043587,0.15603463,0.008284453,-0.065073155,0.4469464,-0.17794195,0.10240583,-0.016754633,0.0582582,-0.12573773,0.0039178864,0.10260599,-0.28352627,0.46535045,-0.0746052,0.12373706,0.06917552,0.017024498,-0.15607125,-0.2063128,0.33518082,-0.047993775,-0.20891322,-0.09345784,-0.27919257,-0.010838178,-0.29986063,-0.069377035,-0.17775688,-0.2386405,-0.19480167,0.15445346,0.20528458,0.05042595,-0.22137621,0.023084028,-0.03572147,-0.0461162,-0.0076188296,0.082257494,-0.16838798,0.13194083,-0.09824066,-0.122986905,0.008206872,-0.17454503,-0.07251578,-0.34976304,-0.109621435,0.0020420114,-0.10966251,-0.10263631,0.040264945,0.037936,-0.10447823,0.112359256,0.074406296,0.031218557,-0.097840466,0.25874192,0.14832975,0.02462145,-0.11972045,0.100787684,-0.115787946,-0.2713493,-0.15013058,0.3052892,-0.08942871,0.26501468,-0.051635228,0.23179194,-0.117855616,0.6252011,-0.09548628,0.07987729,0.07898426,-0.35261092,0.13817759,-0.002757682,-0.39689308,0.10905135,0.111707136,-0.011595691,0.20393075,-0.09260537,-0.15179919,-0.2001358,0.1398312,0.04851631,-0.19738694,0.18956451,0.13789603,-0.00086435315,-0.29782757,-0.029211903,0.020851053,-0.20029499,0.09921507,-0.131983,0.2608193,-0.098570086,0.18118659,0.12597655,-0.15697044,0.043296944,-0.074423745,0.15379825,0.13183062,-0.13664061,0.113863915,0.09775505,-0.37019226,-0.10444691,0.18895759,0.35467452,-0.471109,0.22248715,0.23921894,0.19246568,-0.16593237,-0.13486788,-0.06637506,-0.0022545604,-0.3302758,-0.30637982,-0.04418299,-0.042354178,0.0026002885,-0.052916806,0.064467564,0.105804585,0.035046656,0.0348909,0.0024145036,-0.034075506,0.1739739,-0.18109992,-0.07559335,0.051221117,-0.1751659,-0.12330529,0.15649746,-0.4618017,0.16588117,0.11142563,0.12723342,0.18309788,0.031823203,-0.00047466034,-0.21842332,0.059628155,0.0039997636,-0.14870526,-0.3948714,0.1693991,-0.09596813,0.2138614,0.30494544,-0.07557501,-0.0023500354,0.20387922,-0.124381565,-0.052192964,-0.01537172,0.18238597,-0.07731804,0.070539705,-0.015552879,-0.039474536,0.20908022,-0.14471824,0.1263397,0.1230795,-0.017528422,0.1311703,-0.06057813,-0.008662206,-0.06806935,-0.10956399,-0.21736676,-0.018837957,-0.11787415,-0.20004518,-0.21627283,-0.09215125,0.053359248,0.26228377,0.035491932,0.22925915,0.054367796,0.031128954,0.048207674,-0.057944953,-0.09134648,0.02645273,0.043051194,-0.3387907,-0.19972785,0.1831181,0.029313982,-0.12737103,-0.32529098,-0.060800552,0.041706745,-0.19292925,0.15020116,-0.068609364]'),
 (0.7873187295489029,
  'd8a8750d-c0ff-4126-b775-7a23ce76582a',
  datetime.datetime(2023, 12, 10, 9, 32, 0, 340352),
  datetime.datetime(2023, 12, 10, 9, 32, 0, 340354),
  'e87d6e67-fe84-40ae-b565-f87e472f98a7',
  '0707cbb7-bd81-4d68-89b6-f976c6b18d97',
  '[0.080535844,0.36826453,-0.048618488,-0.040966578,-0.08469625,-0.2414184,-0.2208691,0.31693885,-0.025989788,0.22722593,0.07378795,-0.4371941,-0.18434623,0.28798804,-0.21091804,-0.18234074,-0.14437471,0.077299185,0.25741285,-0.043899078,0.1710619,0.088159926,0.34370703,-0.034831546,-0.06500571,-0.01675584,-0.3593843,-0.12483032,-0.07245333,-0.2814637,0.2424878,0.03732585,0.2489825,0.0066319667,-0.030188974,0.29165438,-0.14384711,0.18971185,0.03221675,0.269909,-0.035448223,-0.18533811,0.13838482,0.2886741,-0.05387127,-0.07958515,-0.026396295,-0.16076659,-0.0337355,-0.49860045,-0.08895147,-0.24265848,-0.18837476,-0.20282717,0.116393335,0.012465722,0.26900277,-0.09876352,-0.10025023,-0.01560155,0.26621157,0.11147674,-0.28237823,0.40609646,0.043979604,-0.2670618,0.15766695,0.3124872,0.19320033,-0.23975219,0.019841518,-0.3592586,0.14022544,0.18665405,0.2956528,0.38026592,0.09181692,0.037383072,0.41949162,-0.19280377,0.13583294,-0.08961974,0.111927345,0.104255505,0.016777603,0.31368187,-0.034689497,0.03158671,0.054008227,0.028883886,0.134974,-0.40061003,0.06805939,-0.27647835,-0.07155708,0.08943493,-0.084973976,-0.23144603,0.25147206,0.4062547,-0.13603058,-0.04721347,-0.24974208,0.014471061,0.007239406,-0.29115358,-0.008248475,-0.19986196,0.29779324,0.15503998,0.05193623,0.1200621,-0.15171432,0.0025147775,0.16174874,0.39281756,-0.059518512,-0.101662315,0.25139025,0.24278536,-0.25985098,-0.17866266,0.15074737,-0.18895325,0.21402416,-0.031533323,-0.010364043,0.05130115,0.2829129,0.048294347,0.30316752,0.13047619,-0.0737172,0.06544186,-0.021524344,-0.14274633,0.12279413,0.043340188,-0.0836821,0.20686556,0.050896008,0.10611267,-0.15247831,0.01646148,-0.35415882,0.16514833,-0.24938154,-0.036970068,0.016177075,0.025029153,0.031585142,-0.027747247,0.13484968,-0.072133064,0.04392868,0.010097283,0.26006192,0.105712734,-0.012386576,-0.1068125,-0.065005474,0.13925524,0.24752511,0.10683777,0.019949978,-0.28247812,0.06790788,-0.31185314,-0.14780928,0.22452745,0.2502993,-0.34732035,0.3046755,0.024136562,0.047353886,-0.0061947703,0.08058989,0.159339,0.054470174,-0.10614421,0.5118677,-0.23604928,0.1352175,-0.088679925,0.083286,-0.15396847,-0.018499753,0.06036139,-0.3657289,0.54237,-0.0946705,0.18207872,0.06079456,0.0144908,-0.21728921,-0.24310501,0.41142353,-0.0809839,-0.2828081,-0.06683921,-0.29072386,-0.060747262,-0.33961862,-0.07284322,-0.24516645,-0.26671442,-0.234694,0.15362693,0.24637593,0.083833896,-0.2675402,-0.03805707,-0.034278426,-0.061641093,-0.005907444,0.07318367,-0.18940292,0.16859683,-0.14777417,-0.19968678,0.02706288,-0.14598016,-0.05950883,-0.36237618,-0.17245616,0.011918166,-0.10561501,-0.07365312,0.09069028,0.103866585,-0.07130297,0.12083256,0.062679924,0.056665782,-0.11792027,0.261854,0.15438497,0.06199481,-0.14676817,0.08827733,-0.15054953,-0.28200823,-0.18203054,0.32914403,-0.055065215,0.2908034,-0.094099775,0.23455288,-0.08208452,0.56750304,-0.10595466,0.07428443,0.12114305,-0.353684,0.15938398,-0.014351889,-0.4020709,0.1590292,0.13783774,-0.02852538,0.20789108,-0.10825761,-0.13470462,-0.2203428,0.13723706,-0.02015565,-0.1956757,0.26120266,0.11849912,0.021986438,-0.31643185,-0.06406413,0.025159944,-0.23550478,0.04615422,-0.14582059,0.2425363,-0.09097769,0.17777273,0.18688749,-0.21825314,0.04666144,-0.053366274,0.2094731,0.18300666,-0.1553514,0.15031219,0.0325041,-0.3741748,-0.07918043,0.17245094,0.3374324,-0.56443673,0.2587615,0.2254415,0.23753121,-0.17006092,-0.15850131,-0.06600238,0.008595747,-0.36447224,-0.25763968,-0.1398258,0.041709214,0.038003076,-0.032688808,0.06908073,0.13002197,-0.017093623,0.07468615,0.030315718,-0.013589805,0.17037249,-0.22934918,-0.06699252,0.00043198094,-0.15522401,-0.18409227,0.15177731,-0.4484028,0.2024828,0.1317046,0.18030474,0.2054251,-0.016872186,0.034901105,-0.23661067,0.055745613,0.019541208,-0.13001166,-0.41103867,0.123015895,-0.115812704,0.21225,0.3214381,-0.038351946,-0.05809598,0.2338426,-0.08942218,-0.014830141,-0.0077087814,0.1976641,-0.09599264,0.12759233,-0.01946843,-0.048617713,0.24907489,-0.08537795,0.13459079,0.13364746,-0.008607486,0.10806607,-0.047254194,-0.010335139,-0.032603007,-0.097966544,-0.24963555,-0.06248435,-0.07617069,-0.18788967,-0.29069677,-0.11804922,0.04252808,0.2885349,-0.008923172,0.26865053,0.0294613,0.03481453,0.0620202,-0.07579853,-0.085006475,-0.011258903,0.028699871,-0.4077699,-0.13936363,0.22927761,0.034479123,-0.14293273,-0.3419612,-0.07814132,-0.027311878,-0.2127496,0.16240236,-0.07051254]'),
 (0.8464764941895635,
  '214ce62b-b3be-4fef-8a73-d41fcafdedca',
  datetime.datetime(2023, 12, 13, 3, 5, 38, 795636),
  datetime.datetime(2023, 12, 13, 3, 5, 38, 795639),
  'e171a95a-5292-4801-b3b1-6f5120a6f883',
  '0707cbb7-bd81-4d68-89b6-f976c6b18d97',
  '[0.07687479,0.3703499,-0.016344389,-0.029648516,-0.12764482,-0.2772647,-0.20949635,0.2919478,-0.011753493,0.23461184,0.10627596,-0.39695427,-0.17670755,0.28700712,-0.21446803,-0.18687066,-0.11362454,0.045986503,0.25650272,-0.020089246,0.1650827,0.065899186,0.2898858,-0.022045087,-0.078169726,-0.01678593,-0.28485185,-0.09650557,-0.07816229,-0.23358928,0.19938457,0.011067409,0.21257055,-0.012112124,-0.046663266,0.27680376,-0.13814874,0.14556836,0.05006448,0.25652373,-0.01460542,-0.17263058,0.13879806,0.28125128,-0.02054115,-0.01767109,-0.016399238,-0.16520593,-0.032296594,-0.48655757,-0.09408431,-0.25992268,-0.16883104,-0.19280241,0.12089983,0.026500821,0.24743974,-0.13457169,-0.10011564,0.0075846976,0.2770566,0.08914281,-0.25508642,0.37326524,-0.004289777,-0.22868703,0.15643586,0.19319361,0.19580054,-0.23034492,0.014399122,-0.32075533,0.16358486,0.15339436,0.26876348,0.30850607,0.085532375,0.04945245,0.35507464,-0.15674719,0.1847093,-0.07384281,0.121012904,0.08551099,0.0132803535,0.34818274,-0.036873665,0.06200787,0.071633,-0.009652865,0.11691133,-0.34718424,0.05896628,-0.28049952,-0.07394543,0.1173159,-0.07905847,-0.20265894,0.22861782,0.40850428,-0.12033167,-0.041488834,-0.19703837,0.026208239,0.009283541,-0.26803684,0.00460146,-0.14278904,0.26466456,0.18388183,0.03519739,0.099244334,-0.1336024,0.015051881,0.14939836,0.32870275,-0.006757051,-0.089798436,0.21526873,0.23167598,-0.21629316,-0.19824468,0.13759962,-0.19332372,0.24183917,-0.0063315276,0.0044571683,0.068284206,0.267638,0.051365264,0.29830933,0.13110419,-0.0995082,0.04968781,-0.035111647,-0.15196928,0.07424043,0.005597854,-0.09560887,0.13896635,0.054864917,0.100839555,-0.1801709,-0.006269796,-0.2705307,0.15421648,-0.26971132,-0.028314915,0.02016126,0.03810799,0.088490956,-0.04037091,0.12807998,-0.024197351,0.077519365,-0.033976063,0.25023896,0.070537835,0.044765644,-0.10097287,-0.092395484,0.13235404,0.20680879,0.08815122,0.018330982,-0.2302677,0.08611671,-0.30531248,-0.115508094,0.1982836,0.25165796,-0.32537282,0.30815285,0.07186559,-0.005004802,0.003955193,0.10022986,0.15148728,0.031870134,-0.0994798,0.42688137,-0.18612687,0.094435446,-0.03460953,0.052366313,-0.17815286,-0.018631535,0.07169855,-0.27838704,0.5209291,-0.13517956,0.14729299,0.11410013,-0.02454583,-0.21939692,-0.25776684,0.3714751,-0.088751815,-0.23900522,-0.09362597,-0.26125252,-0.04305266,-0.34719425,-0.0566709,-0.23226072,-0.2385661,-0.22324689,0.1431453,0.21101697,0.05116935,-0.24359629,-0.02119989,-0.052380353,-0.024812585,-0.012330921,0.11092813,-0.18844795,0.13888949,-0.11807757,-0.15980566,0.02112014,-0.17594387,-0.052582618,-0.35039163,-0.13557275,-0.014376403,-0.09864509,-0.048674874,0.059819117,0.086779304,-0.11127431,0.14622463,0.068919316,0.006297634,-0.08459367,0.22419381,0.11580476,0.041392103,-0.15270716,0.1419755,-0.11045985,-0.2894089,-0.18056679,0.2980525,-0.06889263,0.232319,-0.07066063,0.23364474,-0.09777029,0.5436155,-0.050136052,0.030674078,0.08354012,-0.34082744,0.112927325,-0.03018803,-0.3882058,0.15254374,0.10687539,0.0027761054,0.22193095,-0.10713058,-0.1380258,-0.1995195,0.119310826,0.021455366,-0.18447632,0.22460638,0.14041106,0.045778576,-0.29422045,-0.020943537,-0.0073423004,-0.20913693,0.08098843,-0.15739389,0.25092888,-0.10143916,0.21925306,0.17177269,-0.20019032,0.03768437,-0.052650165,0.18954822,0.18555969,-0.1381121,0.13010335,0.053012554,-0.35027856,-0.06849674,0.17714876,0.3693425,-0.4348499,0.2308126,0.21588936,0.23500201,-0.13426772,-0.17423187,-0.059688948,0.016256975,-0.33500704,-0.27107427,-0.11980403,0.0005144046,0.020324977,-0.040225722,0.061142303,0.10712721,-0.016997697,0.04362048,-0.00584471,-0.044254877,0.1646263,-0.20486195,-0.0866141,0.038618345,-0.1362676,-0.14002967,0.16056919,-0.454176,0.17386772,0.11225753,0.1333197,0.1765974,0.014045747,0.011396703,-0.19834416,0.053213455,0.020756757,-0.16463785,-0.43414038,0.1357436,-0.08698935,0.20916076,0.31123298,-0.03694662,-0.05850741,0.22068454,-0.11206663,-0.00644652,-0.044524737,0.13683373,-0.061378192,0.07990426,-0.009315681,-0.013821895,0.19180828,-0.12299069,0.09425785,0.07732824,-0.016420845,0.0896838,-0.0533576,-0.02810074,-0.023493377,-0.08942259,-0.24751823,-0.04600291,-0.05812494,-0.20172061,-0.23916066,-0.10335071,0.059344463,0.3184261,0.029406851,0.24591576,0.029601445,0.01428427,0.052936886,-0.05406363,-0.11516375,0.06026876,0.015522221,-0.36751926,-0.17491406,0.19709359,0.029885598,-0.16180758,-0.31302452,-0.057244495,0.0213883,-0.18535268,0.12406746,-0.05301358]'),
 (0.9204654585922417,
  'dfb15b5a-c41f-4893-b5f6-c33b65b2a956',
  datetime.datetime(2023, 12, 10, 9, 24, 1, 449478),
  datetime.datetime(2023, 12, 10, 9, 24, 1, 449481),
  '3098d006-968a-4500-ad7b-dd7d860f1a74',
  '0707cbb7-bd81-4d68-89b6-f976c6b18d97',
  '[0.13896362,0.38525656,0.012527571,-0.015070006,-0.12293221,-0.28951672,-0.26681456,0.31661034,-0.07664257,0.2620486,0.061462726,-0.40153986,-0.20921682,0.29799077,-0.1971285,-0.18202698,-0.18010949,0.04682529,0.27701077,-0.003728578,0.21501647,0.10909043,0.36040527,-0.040053863,-0.07318334,-0.026279232,-0.3247676,-0.1134809,-0.074775286,-0.28245512,0.2406062,0.0001737502,0.2089568,-0.014251029,-0.05942294,0.33608764,-0.13966177,0.16529608,0.02864747,0.30183786,-0.011970139,-0.23018019,0.16468851,0.26313654,-0.06349105,-0.0699906,-0.04206139,-0.17865436,-0.046159364,-0.5522608,-0.078912385,-0.29972294,-0.16175638,-0.22832087,0.08739247,0.052880008,0.28603345,-0.09671362,-0.08700992,-0.043471325,0.25611293,0.12589516,-0.2747133,0.49263462,0.043605532,-0.2510881,0.1592331,0.31735906,0.24948469,-0.28051063,0.047432385,-0.3626327,0.15090337,0.19157684,0.27586788,0.33227727,0.09585665,0.07521833,0.43470243,-0.2173761,0.17552379,-0.08425029,0.10766615,0.14026543,0.039451063,0.34305334,-0.061978307,0.026196836,0.031175187,0.02531488,0.11387289,-0.34831238,0.029836455,-0.3218155,-0.058048446,0.06926552,-0.10072453,-0.2666602,0.23072343,0.3787509,-0.1725798,-0.029097307,-0.24118888,0.027925167,-0.010885173,-0.24392621,0.019434342,-0.2036872,0.3033723,0.21250553,0.07202251,0.12749153,-0.15673032,-0.023462977,0.19529757,0.41950917,-0.057421494,-0.11844356,0.28491658,0.23344085,-0.25263363,-0.18169677,0.13321576,-0.21873367,0.20555131,0.0315847,0.025961518,0.01888522,0.24937518,0.13069043,0.30543286,0.1033206,-0.11817533,0.070609555,-0.026309134,-0.13008645,0.14228639,-0.019347517,-0.08190506,0.21247944,0.11520366,0.07092216,-0.1476382,-0.027062422,-0.30227992,0.14520991,-0.2132782,-0.039526265,0.02725021,0.046085868,0.03258404,0.0013501948,0.13035104,-0.08189607,0.06470591,-0.00010338692,0.25020644,0.06539326,0.057030905,-0.13528833,-0.09345966,0.110586606,0.26226392,0.119688995,-0.023768421,-0.23566572,0.06555358,-0.3698549,-0.14254045,0.20019822,0.26968303,-0.3561071,0.31457108,0.026549058,0.057513993,-0.0076393792,0.16079974,0.14792337,0.0488951,-0.12547553,0.50058526,-0.20697536,0.18125863,-0.09362304,0.11315266,-0.19712225,-0.013128722,0.041820318,-0.37682313,0.58342457,-0.06585405,0.15931462,0.08988253,-0.011103453,-0.23100509,-0.23033793,0.41710162,-0.14425275,-0.27730975,-0.08132732,-0.28834003,-0.06023956,-0.33828416,-0.041741405,-0.29619816,-0.28574154,-0.23724072,0.1930234,0.23918302,0.06754215,-0.24659145,-0.014527832,-0.014778483,-0.05792856,0.023475517,0.09042941,-0.18048356,0.21497585,-0.0735045,-0.20629527,0.017335776,-0.117734246,-0.07258761,-0.3338453,-0.11698638,0.05756292,-0.11809615,-0.083350725,0.09072478,0.107007064,-0.11595131,0.08285789,0.07039324,-0.0004789506,-0.0880306,0.31981125,0.15147546,0.051868413,-0.18547127,0.19806705,-0.16764519,-0.32748476,-0.1947733,0.32963833,-0.073281236,0.26661202,-0.08549409,0.21296783,-0.10443024,0.5669302,-0.06611952,0.087796435,0.1327108,-0.37025902,0.13674602,-0.028391242,-0.38014606,0.12612334,0.110663295,-0.03776407,0.19901212,-0.18410674,-0.124954514,-0.18971159,0.16516623,0.0077885007,-0.17194292,0.2382779,0.1389899,0.03885282,-0.34086365,-0.06990831,0.034061857,-0.21117897,0.03958221,-0.13905501,0.27121502,-0.10546665,0.20891428,0.1469512,-0.21348926,0.090166375,-0.10017956,0.21050932,0.1773328,-0.12456914,0.15294576,0.027031396,-0.43273172,-0.078351185,0.18974127,0.3271678,-0.49898246,0.23005673,0.26140237,0.28454107,-0.17093359,-0.2386799,-0.11289645,-0.030708538,-0.38465276,-0.34057385,-0.1409456,0.005361244,0.011217126,-0.029373897,0.049597703,0.118797176,-0.095025524,0.08125037,0.026370244,-0.074322365,0.23244968,-0.2553564,-0.106316194,0.016956944,-0.14338228,-0.2304531,0.16859965,-0.42578697,0.18865584,0.15345235,0.22252737,0.17895581,-0.0025555345,-0.010931447,-0.25591043,0.09472208,0.010877764,-0.14856671,-0.41671798,0.122230984,-0.11260938,0.24627921,0.29121324,-0.08758812,-0.035033043,0.25366348,-0.06584691,-0.03645755,0.0010984614,0.1502682,-0.110920794,0.12373296,-0.03268892,-0.04377607,0.27959463,-0.096555196,0.107148275,0.15930691,-0.04083457,0.09754634,-0.04950251,0.0014476435,-0.0030546635,-0.16220258,-0.2712772,-0.0675803,-0.084725134,-0.15808009,-0.3392358,-0.032903872,0.07014859,0.2925353,-0.0047699935,0.23714855,0.06618174,0.055942018,0.08025009,-0.042221256,-0.110342346,0.026187928,0.053886387,-0.42935148,-0.17444742,0.2492754,0.05924615,-0.16880539,-0.35601702,-0.10267616,-0.024115607,-0.183818,0.12281643,-0.03238341]'),
 (0.9296541929289236,
  '9ec81efd-2744-454c-ad88-444855382ae7',
  datetime.datetime(2023, 12, 10, 9, 29, 28, 966093),
  datetime.datetime(2023, 12, 10, 9, 29, 28, 966096),
  'a6a92076-6ea5-4542-84ad-7154327b36dd',
  '0707cbb7-bd81-4d68-89b6-f976c6b18d97',

In [566]:
conn.close()